version: '3'

services:

  ganache:
    container_name: ganache
    image: 'trufflesuite/ganache-cli'
    ports:
      - '8545:8545'
    volumes:
      - ganache:/app/storage
    command: [
      "-m",
      "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat",
      "--accounts",
      "20",
      "--networkId=9",
      "--gasPrice=1",
      "--gasLimit=10000000",
      "--db=/app/storage"
    ]

  ocn-node:
    container_name: ocn-node
    build:
      context: ./docker/ocn-node
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - ocn-node-db

  ocn-node-db:
    image: postgres:latest
    container_name: ocn-node-db
    restart: always
    ports:
      - 5435:5432
    volumes:
      - ocn-node-db:/var/lib/postgresql
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PORT=5432

  emsp-backend:
    container_name: emsp-backend
    build:
      context: ./packages/emsp-backend
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./packages/emsp-backend/:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 3030:3030
    depends_on:
      - emsp-backend-db
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=emsp-backend-db
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=postgres
      - TYPEORM_DATABASE=postgres
      - TYPEORM_PORT=5432
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_LOGGING=false

  emsp-backend-db:
    image: postgres:latest
    container_name: emsp-backend-db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - emsp-backend-db:/var/lib/postgresql
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PORT=5432

volumes:
  ganache:
  emsp-backend-db:
  ocn-node-db:
