version: '2.4'

services:

  ganache:
    container_name: ganache
    image: 'trufflesuite/ganache-cli'
    ports:
      - '8545:8545'
    volumes:
      - ganache:/app/storage
    command: [
      "-m",
      "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat",
      "--accounts",
      "20",
      "--networkId=9",
      "--gasPrice=1",
      "--gasLimit=10000000",
      "--db=/app/storage"
    ]

  ocn-node:
    container_name: ocn-node
    build:
      context: ./docker/ocn-node
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - ocn-node-db

  ocn-node-db:
    image: postgres:latest
    container_name: ocn-node-db
    restart: always
    ports:
      - 5435:5432
    volumes:
      - ocn-node-db:/var/lib/postgresql
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PORT=5432

  emsp-backend:
    container_name: emsp-backend
    build:
      context: ./packages/emsp-backend
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./packages/emsp-backend/:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 3030:3030
    depends_on:
      - emsp-backend-db
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=emsp-backend-db
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=postgres
      - TYPEORM_DATABASE=postgres
      - TYPEORM_PORT=5432
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_LOGGING=false

  emsp-backend-db:
    image: postgres:latest
    container_name: emsp-backend-db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - emsp-backend-db:/var/lib/postgresql
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PORT=5432

  cpo-backend:
    container_name: cpo-backend
    build: https://github.com/energywebfoundation/ocn-tools.git#feat/admin-api 
    volumes:
      - cpo-backend-db:/home/node/app/data
    ports:
      - 3060:3060 # admin port
    environment:
      - OCN_NODE_URL=http://ocn-node:8080
      - OCN_IDENTITY=0x737f5c61de545d32059ce6d5bc72f7d34b9963310adde62ef0f26621266b65dc
      - OCN_STAGE=docker
      - CPO_PORT=3000
      - CPO_ADMIN_PORT=3060
      - CPO_PUBLIC_IP=http://cpo-backend:3000
      - CPO_PARTY_ID=CPO
      - CPO_COUNTRY_CODE=DE
      - CPO_NAME=MockCPO
      - CPO_PREQUALIFY_ASSETS=false
      - CPO_CREATE_DIDS=false
    command: ['node', 'dist/index.js', 'mock', '--cpo']

volumes:
  ganache:
  emsp-backend-db:
  ocn-node-db:
  cpo-backend-db:
